import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {CombatEffects} from '../src/effects.js';
import {RayLighting,raySegment,visibilityPolygon,collectLights} from '../src/lighting.js';
import {createSlash,stepSlash,slashPose} from '../src/combat.js';
import {drawBossCharge,drawBossBolt,drawFireZone,drawBossBurst} from '../src/boss-effects.js';
const elements=new Map(),calls=[];
const get=s=>{if(!elements.has(s))elements.set(s,{style:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},getContext:()=>({}),hidden:true});return elements.get(s)};
const scope={console,Math,CombatEffects,RayLighting,collectLights,createSlash,stepSlash,setTimeout:()=>0,clearTimeout(){},requestAnimationFrame(){},addEventListener(){},document:{querySelector:get,createElement:()=>({getContext:()=>({})})},W:480,H:270,GROUND:.62,music:n=>calls.push(n),sfx(){},toggle(){},assert};
const source=fs.readFileSync('src/duel.js','utf8').replace(/^import .*;$/gm,'');
vm.runInNewContext(source+`
reset();assert.equal(state,'dialogue');attack();assert.equal(player.attack,0);update(1);assert.equal(elapsed,0);
for(let i=0;i<4;i++)advance();assert.equal(state,'play');assert.equal(document.querySelector('#dialogue').hidden,true);
player.x=280;player.y=144;pointer.x=boss.x;pointer.y=boss.y;boss.cd=10;
const beforeSlash=boss.hp;attack();assert.equal(boss.hp,beforeSlash);update(.05);assert.equal(boss.hp,beforeSlash);
for(let i=0;i<30;i++)update(.016);assert.equal(boss.hp,beforeSlash-19);assert.equal(player.slash,null);
player.cool=0;attack();dash();assert.equal(player.slash,null);
reset();for(let i=0;i<4;i++)advance();
boss.cd=100;parry();assert.equal(player.guard,true);assert.equal(player.qi,88);
for(let i=0;i<100;i++)update(.016);assert.equal(player.guard,true);assert.equal(player.parry,0);
player.qi=50;player.inv=0;const wardHp=player.hp;damage(20);assert.equal(player.hp,wardHp-5);assert.equal(player.qi,46);assert.equal(player.guard,true);
player.cool=0;attack();assert.ok(player.slash,'Ward must not block attacks');player.slash=null;player.attack=0;
flight();assert.equal(player.guard,true);const flightQi=player.qi;hitstop=0;update(1);assert.equal(player.qi,flightQi-3);
player.inv=0;player.qi=3;const brokenHp=player.hp;damage(20);assert.equal(player.guard,false);assert.equal(player.hp,brokenHp-20);
player.qi=11;parry();assert.equal(player.guard,false);assert.equal(player.qi,11);
player.qi=100;parry();player.inv=0;const perfectHp=player.hp;damage(20);assert.equal(player.hp,perfectHp);assert.equal(player.parry,0);assert.equal(player.guard,true);
const cancelQi=player.qi;parry();assert.equal(player.guard,false);assert.equal(player.qi,cancelQi);
parry();reset();assert.equal(player.guard,false);assert.equal(player.guardHit,0);for(let i=0;i<4;i++)advance();
flight();assert.equal(player.flying,true);const qi=player.qi;for(let i=0;i<30;i++)update(.016);assert.ok(player.altitude>12);assert.ok(player.qi<qi);
player.qi=.01;update(.016);assert.equal(player.flying,false);for(let i=0;i<60;i++)update(.016);assert.ok(player.altitude<1);
player.qi=0;flight();assert.equal(player.flying,false);cast();assert.equal(shots.filter(x=>x.friendly).length,0);
player.qi=100;cast();assert.equal(shots.filter(x=>x.friendly).length,3);cast();assert.equal(shots.filter(x=>x.friendly).length,3);
player.dao=100;ultimate();assert.equal(swords.length,18);assert.equal(player.dao,0);
player.x=900;player.y=-50;constrain(player);assert.ok(Math.hypot((player.x-240)/193,(player.y-171)/70)<=1.00001);
boss.hp=260;hitBoss(30,0);assert.equal(boss.phase,2);player.inv=0;player.parry=.1;const hp=player.hp;damage(20);assert.equal(player.hp,hp);
hitBoss(10000,0);assert.equal(boss.dead,true);update(1);assert.equal(state,'win');
reset();assert.equal(boss.dead,false);assert.equal(player.flying,false);assert.equal(swords.length,0);assert.equal(state,'dialogue');
console.log('PASS: dialogue gating, flight/landing/drain, insufficient qi, spell cooldown, ultimate, arena boundary, phase change, parry, win and restart');
`,scope);
assert.deepEqual(calls.slice(0,2),['dialogue','battle']);
const fx=new CombatEffects();
for(let i=0;i<100;i++)fx.emit('impact',240,150,0,1);
assert.ok(fx.items.length<=48&&fx.bits.length<=360,'Effects must stay bounded during rapid impacts');
fx.emit('formation',240,150);fx.emit('finale',240,130);fx.update(3);
assert.equal(fx.items.length,0);assert.equal(fx.bits.length,0);
console.log('PASS: effects remain bounded and expire after combat');
console.log('PASS: persistent ward, mitigation/cost, attack and flight compatibility, low-qi break, toggle/reset and reduced flight drain');

assert.equal(raySegment({x:0,y:0},{x:1,y:0},[5,-2],[5,2]),5);
assert.equal(raySegment({x:0,y:0},{x:1,y:0},[-5,-2],[-5,2]),Infinity);
assert.equal(raySegment({x:0,y:0},{x:1,y:0},[0,2],[5,2]),Infinity);
const wall=[[[5,-2],[6,-2],[6,2],[5,2]]];
const polygon=visibilityPolygon({x:0,y:0,radius:20},wall);
assert.ok(polygon.some(([x,y])=>Math.abs(y)<1e-7&&Math.abs(x-5)<1e-7),'Wall must block a ray');
assert.ok(polygon.some(([x,y])=>Math.abs(y)<1e-7&&Math.abs(x+20)<1e-7),'Unobstructed ray must retain its radius');
assert.ok(polygon.every(([x,y])=>Number.isFinite(x+y)&&Math.hypot(x,y)<=20.00001));
const lights=collectLights({x:100,y:100,face:0},{x:200,y:100},Array.from({length:100},()=>({x:120,y:120,friendly:true})),[],[],[],0);
assert.equal(lights.length,16);assert.equal(lights[0].priority,5);
const lighting=new RayLighting(480,270,()=>({getContext:()=>({})}));
assert.equal(lighting.mode,2);lighting.cycle();assert.equal(lighting.mode,0);lighting.draw({},lights);assert.equal(lighting.stats.rays,0);
lighting.cycle();assert.equal(lighting.mode,1);lighting.cycle();assert.equal(lighting.mode,2);
for(let chain=0;chain<3;chain++){
  const slash=createSlash(chain,0),p={x:0,y:0},target={x:40,y:0};let hits=0;
  assert.equal(stepSlash(slash,.04,p,target).hit,false);
  for(let i=0;i<50;i++)if(stepSlash(slash,.016,p,target).hit)hits++;
  assert.equal(hits,1);assert.ok(Number.isFinite(slashPose(slash).angle));
}
const miss=createSlash(0,0);assert.equal(stepSlash(miss,.3,{x:0,y:0},{x:-40,y:0}).hit,false);
const far=createSlash(0,0);assert.equal(stepSlash(far,.3,{x:0,y:0},{x:100,y:0}).hit,false);
console.log('PASS: delayed single-hit slashes, swept contact, cancellation, ray occlusion, light budget and quality modes');

const bossFx=new CombatEffects();
for(const kind of ['bossCast','bossImpact','bossFire','bossPhase'])bossFx.emit(kind,240,140);
assert.equal(bossFx.items.length,4);
assert.ok(bossFx.bits.every(b=>['#ffe1a1','#ef934f','#b64a3d'].includes(b.color)));
const crimsonLights=collectLights({x:100,y:100,face:0},{x:200,y:100},[],[],[],bossFx.items,0);
assert.equal(crimsonLights.filter(l=>l.color.join(',')==='255,140,68').length,4);
let depth=0,drawCalls=0;
const c=new Proxy({}, {get:(_,key)=>{
 if(key==='save')return ()=>depth++;
 if(key==='restore')return ()=>{depth--;assert.ok(depth>=0)};
 return (...args)=>{drawCalls++;for(const arg of args)if(typeof arg==='number')assert.ok(Number.isFinite(arg),String(key))};
},set:()=>true});
for(const t of [0,.1,.5,1]){
 drawBossCharge(c,{x:200,y:150,windup:.65*(1-t)},t);
 drawBossBolt(c,{x:200,y:150,a:0,trail:[{x:185,y:150},{x:195,y:150}]},t);
 for(const hit of [false,true])for(const front of [false,true])drawFireZone(c,{x:200,y:150,life:hit?.15:1.15-t*.85,hit},t,front);
 for(const f of bossFx.items)drawBossBurst(c,{...f,age:f.duration*t});
}
bossFx.front(c);assert.equal(depth,0);assert.ok(drawCalls>100);
bossFx.update(2);assert.equal(bossFx.items.length,0);assert.equal(bossFx.bits.length,0);
console.log('PASS: Boss effect lifetime, crimson lighting, finite drawing coordinates and balanced canvas state');
