const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const heroAtlas=new Image();heroAtlas.src='/assets/hero-atlas.png';
const W=480,H=270,keys={},mouse={x:W/2,y:H/2};let state='menu',last=0,elapsed=0,shake=0,flash=0,sound=true,audio;
const ui={hp:$('#hpBar'),qi:$('#qiBar'),boss:$('#bossBar'),posture:$('#postureBar'),bossHud:$('#bossHud'),phase:$('#phase'),combo:$('#combo'),toast:$('#toast'),ultimate:$('#ultimate'),objective:$('#objective'),result:$('#resultScreen')};
function $(s){return document.querySelector(s)}const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rnd=(a,b)=>a+Math.random()*(b-a);const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const player={x:140,y:164,vx:0,vy:0,hp:100,qi:100,dao:0,face:0,attack:0,attackCd:0,parry:0,dash:0,inv:0,combo:0,maxCombo:0,comboT:0,qcd:0,step:0,chain:0};
const boss={x:344,y:124,hp:360,maxHp:360,posture:0,face:Math.PI,attack:0,cd:1.5,phase:1,stun:0,dead:false,step:0};let particles=[],slashes=[],projectiles=[],pillars=[],spiritSwords=[],rings=[],afterimages=[],motifs=[];
for(let i=0;i<54;i++)motifs.push({x:rnd(0,W),y:rnd(50,H),s:Math.random()<.7?1:2,c:Math.random()});
function reset(){Object.assign(player,{x:140,y:164,vx:0,vy:0,hp:100,qi:100,dao:0,attack:0,attackCd:0,parry:0,dash:0,inv:0,combo:0,maxCombo:0,comboT:0,qcd:0,step:0,chain:0});Object.assign(boss,{x:344,y:124,hp:360,posture:0,attack:0,cd:1.4,phase:1,stun:0,dead:false,step:0});particles=[];slashes=[];projectiles=[];pillars=[];spiritSwords=[];rings=[];afterimages=[];elapsed=0;state='play';ui.result.classList.add('hidden');ui.bossHud.classList.add('visible');toast('赤霄散人 · 请赐教');}
function tone(f=220,d=.08,type='square',vol=.035){if(!sound)return;audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,f*.55),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function burst(x,y,col,n=10,pow=45){for(let i=0;i<n;i++){let a=rnd(0,Math.PI*2),s=rnd(pow*.3,pow);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.18,.55),max:.55,col,size:Math.random()<.65?1:2})}}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),1100)}
function attack(){if(state!=='play'||player.attackCd>0||player.dash>0)return;player.chain=player.comboT>.15?(player.chain+1)%3:0;player.attack=.2;player.attackCd=player.chain===2?.38:.25;player.face=Math.atan2(mouse.y-player.y,mouse.x-player.x);let reach=player.chain===2?38:29;slashes.push({x:player.x+Math.cos(player.face)*5,y:player.y+Math.sin(player.face)*5,a:player.face,life:.2,max:.2,col:player.chain===2?'#f2c76e':'#bce8d5',r:reach,flip:player.chain%2});player.x+=Math.cos(player.face)*(player.chain===2?9:4);player.y+=Math.sin(player.face)*(player.chain===2?9:4);rings.push({x:player.x,y:player.y,r:5,life:.18,max:.18,col:'#8fd0bd'});tone(player.chain===2?190:270,.08,'sawtooth',.03);if(dist(player,boss)<48+(player.chain===2?8:0)&&!boss.dead){let delta=Math.abs(Math.atan2(Math.sin(player.face-Math.atan2(boss.y-player.y,boss.x-player.x)),Math.cos(player.face-Math.atan2(boss.y-player.y,boss.x-player.x))));if(delta<1.15)hitBoss(player.chain===2?28:16,player.chain===2?22:12)}}
function hitBoss(dmg,poise){if(boss.stun>0)dmg*=1.65;boss.hp-=dmg;boss.posture=clamp(boss.posture+poise,0,100);player.combo++;player.comboT=1.7;player.maxCombo=Math.max(player.maxCombo,player.combo);player.dao=clamp(player.dao+7,0,100);player.qi=clamp(player.qi+4,0,100);shake=5;flash=.05;burst(boss.x,boss.y,'#efd28a',14,70);tone(110,.1,'square',.05);if(boss.posture>=100){boss.stun=2.6;boss.posture=0;toast('道心破绽 · 乘势追击');}if(boss.hp<=0){boss.hp=0;boss.dead=true;setTimeout(()=>finish(true),650)}else if(boss.hp<boss.maxHp*.5&&boss.phase===1){boss.phase=2;boss.cd=.3;toast('赤霄散人 · 法相开');}}
function damage(n){if(player.inv>0)return;if(player.parry>0){boss.stun=.8;boss.posture=clamp(boss.posture+24,0,100);player.dao=clamp(player.dao+18,0,100);burst(player.x,player.y,'#fff0a2',24,105);rings.push({x:player.x,y:player.y,r:4,life:.38,max:.38,col:'#ffe49b'});slashes.push({x:player.x,y:player.y,a:boss.face+Math.PI,life:.18,max:.18,col:'#fff2b0',r:34,flip:0});shake=7;toast('完美化解');tone(520,.15,'square',.06);return}player.hp-=n;player.inv=.55;player.combo=0;shake=9;flash=.12;burst(player.x,player.y,'#b43d35',12,55);tone(70,.18,'sawtooth',.06);if(player.hp<=0){player.hp=0;finish(false)}}
function parry(){if(state==='play'&&player.parry<=0){player.parry=.28;tone(380,.05,'triangle',.02)}}function dash(){if(state==='play'&&player.dash<=0&&player.qi>=12){player.dash=.25;player.inv=.3;player.qi-=12;burst(player.x,player.y,'#7da89c',7,20);tone(170,.12,'sine',.025)}}
function cast(){if(state!=='play'||player.qcd>0||player.qi<25)return;player.qi-=25;player.qcd=2.4;let a=Math.atan2(mouse.y-player.y,mouse.x-player.x);projectiles.push({x:player.x,y:player.y,vx:Math.cos(a)*250,vy:Math.sin(a)*250,life:1.5,friendly:true});tone(620,.18,'sine',.04)}
function ultimate(){if(state!=='play'||player.dao<100)return;player.dao=0;boss.stun=1.35;toast('万 剑 归 宗');rings.push({x:player.x,y:player.y,r:8,life:.8,max:.8,col:'#f0d88d'});for(let i=0;i<16;i++){let a=i/16*Math.PI*2;spiritSwords.push({x:boss.x+Math.cos(a)*rnd(70,105),y:boss.y+Math.sin(a)*rnd(45,70),a:a+Math.PI,delay:.18+i*.035,life:1.2,hit:false})}tone(880,.5,'sawtooth',.045)}
function finish(win){state=win?'win':'lose';ui.bossHud.classList.remove('visible');$('#resultKicker').textContent=win?'试炼已破':'道途未绝';$('#resultTitle').textContent=win?'道心通明':'胜败亦是修行';$('#timeStat').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;$('#comboStat').textContent=player.maxCombo;setTimeout(()=>ui.result.classList.remove('hidden'),450)}
function update(dt){if(state!=='play')return;elapsed+=dt;for(let k of ['attack','attackCd','parry','dash','inv','comboT','qcd'])player[k]=Math.max(0,player[k]-dt);boss.attack=Math.max(0,boss.attack-dt);boss.stun=Math.max(0,boss.stun-dt);if(player.comboT<=0)player.combo=0;let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0),l=Math.hypot(dx,dy)||1,s=player.dash>0?220:80;if(player.dash>0&&dx===0&&dy===0){dx=Math.cos(player.face);dy=Math.sin(player.face);l=1}player.vx+=(dx/l*s-player.vx)*Math.min(1,dt*14);player.vy+=(dy/l*s-player.vy)*Math.min(1,dt*14);player.x=clamp(player.x+player.vx*dt,26,W-26);player.y=clamp(player.y+player.vy*dt,69,H-23);player.face=Math.atan2(mouse.y-player.y,mouse.x-player.x);player.qi=clamp(player.qi+dt*8,0,100);
 player.step+=Math.hypot(player.vx,player.vy)*dt*.055;boss.step+=dt*3;
 if(player.dash>0&&Math.random()<.55)afterimages.push({x:player.x,y:player.y,face:player.face,life:.2,max:.2,hero:true});
 if(!boss.dead&&boss.stun<=0){let d=dist(player,boss),a=Math.atan2(player.y-boss.y,player.x-boss.x);boss.face=a;boss.cd-=dt;if(boss.attack<=0&&d>47){let sp=boss.phase===2?47:37;boss.x+=Math.cos(a)*sp*dt;boss.y+=Math.sin(a)*sp*dt}if(boss.cd<=0){if(d<62){boss.attack=.55;boss.cd=boss.phase===2?1.05:1.45;rings.push({x:boss.x,y:boss.y,r:12,life:.45,max:.45,col:'#cf6047'});setTimeout(()=>{if(state==='play'&&boss.attack>0&&dist(player,boss)<70)damage(boss.phase===2?18:14)},330)}else{boss.cd=boss.phase===2?1.25:2;let aa=Math.atan2(player.y-boss.y,player.x-boss.x);projectiles.push({x:boss.x,y:boss.y,vx:Math.cos(aa)*125,vy:Math.sin(aa)*125,life:2.7,friendly:false});if(boss.phase===2&&Math.random()<.7)for(let i=-1;i<=1;i++)pillars.push({x:player.x+i*28,y:player.y,life:1.1,strike:false})}}}
 for(let p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life>0&&dist(p,p.friendly?boss:player)<13){p.life=0;p.friendly?hitBoss(27,20):damage(13);burst(p.x,p.y,p.friendly?'#8ed8cc':'#c25c43',12,65)}}projectiles=projectiles.filter(p=>p.life>0);for(let p of pillars){p.life-=dt;if(p.life<.28&&!p.strike){p.strike=true;if(Math.hypot(player.x-p.x,player.y-p.y)<19)damage(16);burst(p.x,p.y,'#d9774f',18,60)}}pillars=pillars.filter(p=>p.life>0);
 for(let s of spiritSwords){s.delay-=dt;if(s.delay<=0){let a=Math.atan2(boss.y-s.y,boss.x-s.x);s.a=a;s.x+=Math.cos(a)*260*dt;s.y+=Math.sin(a)*260*dt;s.life-=dt;if(!s.hit&&dist(s,boss)<12){s.hit=true;s.life=0;slashes.push({x:boss.x,y:boss.y,a:a,life:.2,max:.2,col:'#f4dc91',r:30,flip:0});hitBoss(7,2)}}}spiritSwords=spiritSwords.filter(s=>s.life>0);
 for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);slashes.forEach(s=>s.life-=dt);slashes=slashes.filter(s=>s.life>0);rings.forEach(r=>{r.life-=dt;r.r+=dt*80});rings=rings.filter(r=>r.life>0);afterimages.forEach(a=>a.life-=dt);afterimages=afterimages.filter(a=>a.life>0);shake=Math.max(0,shake-dt*25);flash=Math.max(0,flash-dt);syncUI()}
function syncUI(){ui.hp.style.width=player.hp+'%';ui.qi.style.width=player.qi+'%';ui.boss.style.width=boss.hp/boss.maxHp*100+'%';ui.posture.style.width=boss.posture+'%';ui.phase.textContent=boss.phase===1?'壹 · 试剑':'贰 · 法相';ui.combo.querySelector('strong').textContent=player.combo;ui.combo.classList.toggle('show',player.combo>1);ui.ultimate.classList.toggle('ready',player.dao>=100);$('#qCd').style.width=(1-player.qcd/2.4)*100+'%';ui.objective.textContent=boss.phase===1?'击败守崖人':'破除赤霄法相'}
function draw(){ctx.save();if(shake)ctx.translate(Math.round(rnd(-shake,shake)),Math.round(rnd(-shake,shake)));sky();ground();for(let p of pillars)drawPillar(p);rings.forEach(drawRing);projectiles.forEach(drawProjectile);spiritSwords.forEach(drawSpiritSword);afterimages.forEach(a=>drawSprite(a,a.hero,a.life/a.max*.22));drawShadow(boss);drawShadow(player);drawFighter(boss,false);drawFighter(player,true);slashes.forEach(drawSlash);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.col;ctx.fillRect(Math.round(p.x),Math.round(p.y),p.size,p.size)});ctx.globalAlpha=1;if(flash){ctx.fillStyle=`rgba(255,236,190,${flash*2})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
function sky(){let g=ctx.createLinearGradient(0,0,0,190);g.addColorStop(0,'#101d27');g.addColorStop(.45,'#30464b');g.addColorStop(.72,'#aa7752');g.addColorStop(1,'#172226');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#d7bf85';ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(391,55,20,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#17242a';ctx.beginPath();ctx.moveTo(0,122);for(let x=0;x<=W;x+=24)ctx.lineTo(x,105+Math.sin(x*.035)*12+Math.sin(x*.09)*5);ctx.lineTo(W,190);ctx.lineTo(0,190);ctx.fill();ctx.fillStyle='#253338';ctx.beginPath();ctx.moveTo(0,145);for(let x=0;x<=W;x+=18)ctx.lineTo(x,132+Math.sin(x*.023+2)*9);ctx.lineTo(W,190);ctx.lineTo(0,190);ctx.fill();for(let x=20;x<W;x+=53){ctx.fillStyle='#11191c';ctx.fillRect(x,104+(x%37),2,55);ctx.fillRect(x-3,105+(x%37),8,2);for(let j=0;j<5;j++){ctx.fillStyle=j%2?'#29403c':'#223634';ctx.fillRect(x-10-j%2*5,112+(x%37)+j*7,13+j*2,2)}}}
function ground(){ctx.fillStyle='#182727';ctx.fillRect(0,158,W,112);ctx.fillStyle='#24342f';ctx.beginPath();ctx.ellipse(250,211,230,65,0,0,7);ctx.fill();ctx.strokeStyle='#65705a33';ctx.lineWidth=1;for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(250,205,50+i*29,11+i*7,0,0,7);ctx.stroke()}for(let m of motifs){if(m.y<160)continue;ctx.fillStyle=m.c>.7?'#9e7652':'#53644b';ctx.fillRect(m.x,m.y,m.s,3+m.s);if(m.c>.85)ctx.fillRect(m.x-1,m.y,3,1)}ctx.fillStyle='#7c6040';for(let i=0;i<24;i++){let a=i/24*6.28;ctx.fillRect(250+Math.cos(a)*108,210+Math.sin(a)*32,2,2)}}
function drawShadow(o){ctx.save();ctx.translate(o.x+4,o.y+7);ctx.scale(1,.32);ctx.fillStyle='#05080988';ctx.beginPath();ctx.arc(0,0,12,0,7);ctx.fill();ctx.restore()}
function spriteFrame(o){let a=((o.face%(Math.PI*2))+Math.PI*2)%(Math.PI*2),col;if(a<Math.PI*.25||a>Math.PI*1.75)col=3;else if(a<Math.PI*.75)col=0;else if(a<Math.PI*1.25)col=2;else col=1;let moving=Math.hypot(o.vx||0,o.vy||0)>12,row=moving?1+(Math.floor(o.step||0)%2):0;return{col,row}}
function drawSprite(o,hero,alpha=1){if(o.dead||!heroAtlas.complete)return;let {col,row}=spriteFrame(o),cell=313.5;ctx.save();ctx.globalAlpha=alpha;ctx.translate(Math.round(o.x),Math.round(o.y));if(!hero)ctx.filter='sepia(1) saturate(2.2) hue-rotate(315deg) brightness(.82)';if(hero&&o.inv>0&&Math.floor(o.inv*20)%2)ctx.globalAlpha*=.45;ctx.drawImage(heroAtlas,col*cell,row*cell,cell,cell,-38,-69,76,76);ctx.restore()}
function drawFighter(o,hero){if(o.dead)return;drawSprite(o,hero);ctx.save();ctx.translate(o.x,o.y);if(hero&&o.parry>0){ctx.strokeStyle='#b7f4df';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-19,25,-1.15,1.15);ctx.stroke();ctx.strokeStyle='#5f9f91';ctx.beginPath();ctx.arc(0,-19,20,-1.15,1.15);ctx.stroke()}if(o.attack>0){ctx.rotate(o.face);ctx.fillStyle=hero?'#e9eee4':'#ff9b68';ctx.fillRect(12,-3,25,2);ctx.fillStyle='#9e744a';ctx.fillRect(7,-3,7,3)}ctx.restore()}
function drawSlash(s){let q=clamp(s.life/(s.max||.2),0,1),r=s.r||27;ctx.save();ctx.globalAlpha=q;ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.scale(1,s.flip?-1:1);ctx.strokeStyle='#ffffff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,r,-.9,.9);ctx.stroke();ctx.strokeStyle=s.col;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,r-3,-.82,.82);ctx.stroke();for(let i=0;i<5;i++){let a=-.75+i*.35;ctx.fillStyle=s.col;ctx.fillRect(Math.cos(a)*(r+3),Math.sin(a)*(r+3),2,2)}ctx.restore()}
function drawRing(r){ctx.save();ctx.globalAlpha=r.life/r.max;ctx.strokeStyle=r.col;ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(r.x,r.y,r.r,r.r*.42,0,0,7);ctx.stroke();ctx.restore()}
function drawSpiritSword(s){ctx.save();ctx.globalAlpha=s.delay>0?.35:1;ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.fillStyle='#f6e5ae';ctx.fillRect(-9,-1,16,2);ctx.fillStyle='#a5d9c9';ctx.fillRect(-7,-2,11,1);ctx.fillStyle='#ba6b46';ctx.fillRect(7,-2,3,4);ctx.restore()}
function drawProjectile(p){ctx.fillStyle=p.friendly?'#9de0d2':'#de6a4a';ctx.fillRect(p.x-3,p.y-3,6,6);ctx.fillStyle='#f4dfaa';ctx.fillRect(p.x-1,p.y-1,2,2)}function drawPillar(p){ctx.globalAlpha=p.life>.3?.45:.9;ctx.fillStyle=p.strike?'#f09a58':'#b8503933';ctx.fillRect(p.x-8,p.y-8,16,16);if(p.strike)ctx.fillRect(p.x-2,60,4,p.y-60);ctx.globalAlpha=1}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyJ')attack();if(e.code==='KeyK')parry();if(e.code==='Space'){e.preventDefault();dash()}if(e.code==='KeyQ')cast();if(e.code==='KeyE')ultimate()});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*W;mouse.y=(e.clientY-r.top)/r.height*H});canvas.addEventListener('mousedown',e=>e.button===0?attack():parry());canvas.addEventListener('contextmenu',e=>e.preventDefault());$('#startButton').onclick=()=>{$('#startScreen').classList.add('hidden');reset()};$('#restartButton').onclick=reset;$('#soundToggle').onclick=()=>{sound=!sound;$('#soundToggle').textContent=sound?'声 ◐':'声 ○'};requestAnimationFrame(loop);
